k get role -n cert-manager cert-manager-istio-csr -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{"nwm.io/contact":"*NWMPlatformEngineering@rbsres07.net"},"labels":{"app.kubernetes.io/instance":"RELEASE-NAME","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"cert-manager-istio-csr","app.kubernetes.io/version":"v0.2.0","helm.sh/chart":"cert-manager-istio-csr-v0.2.1","kustomize.toolkit.fluxcd.io/checksum":"c3f98b1d6f11488efbbcd4b2b379a4a2f7b362f3","kustomize.toolkit.fluxcd.io/name":"gke-cluster-services","kustomize.toolkit.fluxcd.io/namespace":"nwm-flux-system"},"name":"cert-manager-istio-csr","namespace":"cert-manager"},"rules":[{"apiGroups":["cert-manager.io"],"resources":["certificaterequests"],"verbs":["get","list","create","update","delete","watch"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["get","create","update","watch","list"]},{"apiGroups":[""],"resources":["events"],"verbs":["create"]}]}
    nwm.io/contact: '*NWMPlatformEngineering@rbsres07.net'
  creationTimestamp: "2021-08-09T11:42:40Z"
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/version: v0.2.0
    helm.sh/chart: cert-manager-istio-csr-v0.2.1
    kustomize.toolkit.fluxcd.io/checksum: c3f98b1d6f11488efbbcd4b2b379a4a2f7b362f3
    kustomize.toolkit.fluxcd.io/name: gke-cluster-services
    kustomize.toolkit.fluxcd.io/namespace: nwm-flux-system
  name: cert-manager-istio-csr
  namespace: cert-manager
  resourceVersion: "12723918"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/cert-manager/roles/cert-manager-istio-csr
  uid: 71f56171-51dc-4faa-8e62-01ede4206242
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
